### ISSUE TITLE
Prompt for deletion when child is detached

### ISSUE THREAD

**Issue by kkott** [patrickkidd/family-diagram#10]
v.1.0.0b3
MacOS El Capitan v.10.11.6
MacBook Pro, late 2011

I detached a child and dragged it beyond the visible boundary of the diagram. Later, I found it, hanging way over to the right. Should I be prompted to delete at some point?

**Comment by patrickkidd** [comment]
Interesting that you found that intuitive, have you seen that somewhere else? At first glance, implementing this would conflict with the overall workflow to select and move a person or group of people. But it is an interesting idea.

**Comment by kkott** [comment]
Maybe not intuitive. More like being dumb about how to delete.
