### ISSUE TITLE
Edit button for note fields

### ISSUE THREAD

**Issue by kkott** [patrickkidd/family-diagram#5]
v.1.0.0b3
MacOS El Capitan v.10.11.6
MacBook Pro, late 2011
The "edit" button opens a new note field. I would expect "edit" to open an existing note. When you create a note from the note tab, there is no OK button but when you open a note from the edit option, there is.

**Comment by patrickkidd** [comment]
When you double-click a person you get a property sheet for that person, which has a "Notes" tab attached to the person in general. If you go into the "History" tab, you can select an event and then click the edit button to edit that event.

I suppose this means that I should change the text on the event button to "Edit event..."
