### ISSUE TITLE
Keep a symbol selected to add more than one at a time

### ISSUE THREAD

**Issue by kkott** [patrickkidd/family-diagram#7]
v.1.0.0b3
MacOS El Capitan v.10.11.6
MacBook Pro, late 2011

It would be nice if you could keep a symbol (male, female, child) selected until you turn it off so you could add more than one at a time without so much clicking.

**Comment by patrickkidd** [comment]
This is a good idea.

**Comment by patrickkidd** [comment]
I tried this for a bit and then scraped it in favor of adding shortcuts for each object type. This is actually faster if you are adding a lot of different objects. You can see the keyboard shortcuts by looking in the "Insert" menu at the top of the screen.
